### ISSUE TITLE
lmerTest::anova does not seem to work

### ISSUE THREAD

**Issue by toouggy** [runehaubo/lmerTest#7]
Hi,

I tried to run lmerTest::anova function and get the following error:

Error: 'anova' is not an exported object from 'namespace:lmerTest'

The code and data run fine a few months ago.  I tried to rerun today and got the error.  What am I doing wrong?

Thank you.

**Comment by runehaubo** [comment]
The version of `lmerTest` where `anova` is an `S3` _method_ rather than `S4` is here: `runehaubo/lmerTest`.

**Comment by toouggy** [comment]
Thank you again
